name: flutter_gmaps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.4.3'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  google_maps_flutter: ^2.7.0
  geolocator: ^7.7.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0
  flutter_typeahead: ^4.0.0 
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  flutter_polyline_points: ^1.0.0
  http: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
