name: flutter_gmaps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.4.3'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  google_maps_flutter: ^2.7.0
  geolocator: ^7.7.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0
  flutter_typeahead: ^4.0.0 
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  font_awesome_flutter: ^10.0.0
  flutter_polyline_points: ^1.0.0
  http: ^0.13.1
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^1.0.3
  firebase_auth: ^5.1.1
  intl_phone_number_input: ^0.7.4
  firebase_storage: ^12.1.0
  fpdart: ^1.1.0
  image_picker: ^1.1.2
  uuid: ^4.4.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_place: ^0.4.7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/svgs/
  uses-material-design: true

  fonts:
    - family: MaterialIcons