// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0YuPUxkyI7HiR2HoBz_MVY59BhhmI6k',
    appId: '1:726249829127:web:6aa82ad2407f713d7e8ba2',
    messagingSenderId: '726249829127',
    projectId: 'just-sunrise-427601-p4',
    authDomain: 'just-sunrise-427601-p4.firebaseapp.com',
    storageBucket: 'just-sunrise-427601-p4.appspot.com',
    measurementId: 'G-NFKZJX50DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jcerFNkUuz8t32BDvnjysPobj72Pb3s',
    appId: '1:726249829127:android:1703ebe432019d267e8ba2',
    messagingSenderId: '726249829127',
    projectId: 'just-sunrise-427601-p4',
    storageBucket: 'just-sunrise-427601-p4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVV00yspfVvorzUZGvZ7lkMg-ASQXUTo',
    appId: '1:726249829127:ios:12c037ccfaf485557e8ba2',
    messagingSenderId: '726249829127',
    projectId: 'just-sunrise-427601-p4',
    storageBucket: 'just-sunrise-427601-p4.appspot.com',
    iosBundleId: 'com.example.flutterGmaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASVV00yspfVvorzUZGvZ7lkMg-ASQXUTo',
    appId: '1:726249829127:ios:12c037ccfaf485557e8ba2',
    messagingSenderId: '726249829127',
    projectId: 'just-sunrise-427601-p4',
    storageBucket: 'just-sunrise-427601-p4.appspot.com',
    iosBundleId: 'com.example.flutterGmaps',
  );
}
